"""Add BOM table

Revision ID: 13fbc714e7df
Revises: f3b501476530
Create Date: 2024-11-19 06:11:45.482886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13fbc714e7df'
down_revision = 'f3b501476530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bom',
    sa.Column('id_bom', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('cantidad_por_producto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_material'], ['materiales.id_material'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_bom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bom')
    # ### end Alembic commands ###
