"""Inicialización de migraciones

Revision ID: 96cba2ba1d58
Revises: 
Create Date: 2024-11-19 05:45:53.838942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96cba2ba1d58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario',
    sa.Column('id_inventario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_material', sa.Integer(), nullable=False),
    sa.Column('cantidad_disponible', sa.Integer(), nullable=False),
    sa.Column('cantidad_requerida', sa.Integer(), nullable=False),
    sa.Column('fecha_reabastecimiento', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id_inventario')
    )
    op.create_table('lugar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_producto', sa.String(length=128), nullable=False),
    sa.Column('demanda_planeada', sa.Integer(), nullable=True),
    sa.Column('fecha_entrega', sa.Date(), nullable=True),
    sa.Column('cantidad_producir', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_table('recursos',
    sa.Column('id_recurso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_recurso', sa.String(length=128), nullable=False),
    sa.Column('disponibilidad', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_recurso')
    )
    op.create_table('persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_identidad', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('apellidos', sa.String(length=64), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('cantidad_mascotas', sa.Integer(), nullable=False),
    sa.Column('semana_inicio', sa.String(length=10), nullable=False),
    sa.Column('lugar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lugar_id'], ['lugar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('persona')
    op.drop_table('recursos')
    op.drop_table('productos')
    op.drop_table('lugar')
    op.drop_table('inventario')
    # ### end Alembic commands ###
