"""Add calendario_produccion table

Revision ID: 9e1e09f64938
Revises: b1951c1d40a3
Create Date: 2024-11-19 07:27:39.895087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1e09f64938'
down_revision = 'b1951c1d40a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendario_de_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semana', sa.String(length=20), nullable=False),
    sa.Column('capacidad_disponible', sa.Integer(), nullable=False),
    sa.Column('produccion_programada', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendario_de_produccion')
    # ### end Alembic commands ###
