"""Add ordenes_compra table

Revision ID: c4eb57967e62
Revises: 13fbc714e7df
Create Date: 2024-11-19 06:27:54.555491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4eb57967e62'
down_revision = '13fbc714e7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ordenes_compra',
    sa.Column('id_orden_compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('material_solicitado', sa.Integer(), nullable=False),
    sa.Column('cantidad_ordenada', sa.Integer(), nullable=False),
    sa.Column('fecha_entrega_esperada', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['material_solicitado'], ['materiales.id_material'], ),
    sa.PrimaryKeyConstraint('id_orden_compra')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ordenes_compra')
    # ### end Alembic commands ###
