"""Add orden_produccion table

Revision ID: c5b9ff791402
Revises: c4eb57967e62
Create Date: 2024-11-19 06:34:01.157599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5b9ff791402'
down_revision = 'c4eb57967e62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orden_produccion',
    sa.Column('id_orden', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_asociado', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio_produccion', sa.Date(), nullable=False),
    sa.Column('fecha_fin_produccion', sa.Date(), nullable=False),
    sa.Column('cantidad_ordenada', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_asociado'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orden_produccion')
    # ### end Alembic commands ###
