"""Add centros_trabajo table

Revision ID: e9d009ce36eb
Revises: c5b9ff791402
Create Date: 2024-11-19 06:43:34.662364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d009ce36eb'
down_revision = 'c5b9ff791402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centros_trabajo',
    sa.Column('id_centro_trabajo', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_centro_trabajo', sa.String(length=128), nullable=False),
    sa.Column('capacidad_teorica', sa.Integer(), nullable=False),
    sa.Column('capacidad_real', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_centro_trabajo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('centros_trabajo')
    # ### end Alembic commands ###
